classes = ["Glass,Fire,Wood Charred Fairy",
"Glass,Fire,Lightning Wizard",
"Glass,Fire,Death Infernalist",
"Glass,Fire,Bubble High wizard",
"Glass,Fire,Metal Archon",
"Glass,Fire,Ice Wizard",
"Glass,Fire,Heart Bard",
"Glass,Wood,Lightning Druid",
"Glass,Wood,Death Grim Reaper",
"Glass,Wood,Bubble Fairy",
"Glass,Wood,Metal Gardener",
"Glass,Wood,Ice Trapper",
"Glass,Wood,Heart Sprite",
"Glass,Lightning,Death Duelist",
"Glass,Lightning,Bubble High Wizard",
"Glass,Lightning,Metal Phalanx",
"Glass,Lightning,Ice Weather Witch",
"Glass,Lightning,Heart Valkyrie",
"Glass,Death,Bubble Dark Fairy",
"Glass,Death,Metal Death Knight",
"Glass,Death,Ice Necromancer",
"Glass,Death,Heart Psychopomp",
"Glass,Bubble,Metal Dispeller",
"Glass,Bubble,Ice Escapist",
"Glass,Bubble,Heart Light Fairy",
"Glass,Metal,Ice Sherpa",
"Glass,Metal,Heart Cleric",
"Glass,Ice,Heart Interloper",
"Fire,Wood,Lightning Naturalist",
"Fire,Wood,Death Unkempt Druid",
"Fire,Wood,Bubble Charred Fairy",
"Fire,Wood,Metal Blacksmith",
"Fire,Wood,Ice Hag",
"Fire,Wood,Heart Bard",
"Fire,Lightning,Death Warlock",
"Fire,Lightning,Bubble High Wizard",
"Fire,Lightning,Metal Battlemage",
"Fire,Lightning,Ice Elementalist",
"Fire,Lightning,Heart Shaman",
"Fire,Death,Bubble Dark Wizard",
"Fire,Death,Metal Death Knight",
"Fire,Death,Ice Horseman",
"Fire,Death,Heart Sorcerer",
"Fire,Bubble,Metal General",
"Fire,Bubble,Ice Sorcerer",
"Fire,Bubble,Heart Sorcerer",
"Fire,Metal,Ice Enchanter",
"Fire,Metal,Heart Crusader",
"Fire,Ice,Heart Sorcerer",
"Wood,Lightning,Death Shaman",
"Wood,Lightning,Bubble Stormcaller",
"Wood,Lightning,Metal Ranger",
"Wood,Lightning,Ice Druid",
"Wood,Lightning,Heart Druid",
"Wood,Death,Bubble Undead Fairy",
"Wood,Death,Metal Vale Knight",
"Wood,Death,Ice Undertaker",
"Wood,Death,Heart Shaman",
"Wood,Bubble,Metal Scientist",
"Wood,Bubble,Ice Trapper",
"Wood,Bubble,Heart Druid",
"Wood,Metal,Ice Ranger",
"Wood,Metal,Heart Ranger",
"Wood,Ice,Heart Hedge Witch",
"Lightning,Death,Bubble Dark Wizard",
"Lightning,Death,Metal Undead Archer",
"Lightning,Death,Ice Undead Pirate",
"Lightning,Death,Heart Sorcerer",
"Lightning,Bubble,Metal Elemental Archer",
"Lightning,Bubble,Ice Fury",
"Lightning,Bubble,Heart Genie",
"Lightning,Metal,Ice Stormcaller",
"Lightning,Metal,Heart Enchanted Archer",
"Lightning,Ice,Heart Soothsayer",
"Death,Bubble,Metal Undead Provisioner",
"Death,Bubble,Ice Sorcerer",
"Death,Bubble,Heart Wild Mage",
"Death,Metal,Ice Draugr",
"Death,Metal,Heart Forsaken Paladin",
"Death,Ice,Heart Ferryman",
"Bubble,Metal,Ice Cold King",
"Bubble,Metal,Heart Healer",
"Bubble,Ice,Heart Alchemist",
"Metal,Ice,Heart Icy Architect"]

dict = {}
for string in classes:
    arr = string.split(" ")
    elements = "".join(arr[0])
    class_name = " ".join(arr[1:])
    if class_name not in dict:
        dict[class_name] = [elements]
    else:
        dict[class_name].append(elements)

for k,v in dict.items():
    if len(v) > 1:
        print(k,v)
